name: Sign existing release assets

on:
  release:
    types: [published, edited]

permissions:
  contents: write
  id-token: write

jobs:
  sign-assets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install cosign
        uses: sigstore/cosign-installer@d7543c93d881b35a8faa02e8e3605f69b7a1ce62

      - name: Download release assets
        env:
          GH_TOKEN: ${{ github.token }}  # Use built-in token instead of PAT
        run: |
          set -euo pipefail
          mkdir -p dist
          echo "Tag: ${{ github.event.release.tag_name }}"
          echo "Repo: ${{ github.repository }}"
          gh release download "${{ github.event.release.tag_name }}" --dir dist

      - name: Sign assets with cosign (keyless)
        env:
          COSIGN_YES: "true"
        run: |
          set -euo pipefail
          shopt -s nullglob
          for f in dist/*; do
            case "$f" in
              *.sig|*.pem|*.bundle.json) continue;;
            esac
            echo "Signing: $f"
            cosign sign-blob "$f" \
              --bundle "$f.sig.bundle.json" \
              --output-signature "$f.sig" \
              --output-certificate "$f.pem"
          done

      - name: Upload signatures back to the release
        env:
          GH_TOKEN: ${{ github.token }}  # Use built-in token
        run: |
          set -euo pipefail
          shopt -s nullglob
          gh release upload "${{ github.event.release.tag_name }}" \
            dist/*.sig dist/*.pem dist/*.sig.bundle.json \
            --clobber
